export type StudioPageContentData = {
  id: string;
  eyebrow: string;
  title: string;
  intro: string;
  founderOneName: string;
  founderOneRole: string;
  founderOneDescription: string;
  founderOneImageUrl: string;
  founderOneImageAssetId: string | null;
  founderOneImageAlt: string | null;
  founderTwoName: string;
  founderTwoRole: string;
  founderTwoDescription: string;
  founderTwoImageUrl: string;
  founderTwoImageAssetId: string | null;
  founderTwoImageAlt: string | null;
  historyTitle: string;
  historyContentHtml: string;
  translations: {
    locale: string;
    eyebrow: string | null;
    title: string | null;
    intro: string | null;
    founderOneName: string | null;
    founderOneRole: string | null;
    founderOneDescription: string | null;
    founderOneImageAlt: string | null;
    founderTwoName: string | null;
    founderTwoRole: string | null;
    founderTwoDescription: string | null;
    founderTwoImageAlt: string | null;
    historyTitle: string | null;
    historyContentHtml: string | null;
  }[];
};
