export type StudioPageContentData = {
  id: string;
  eyebrow: string;
  eyebrowEn: string | null;
  title: string;
  titleEn: string | null;
  intro: string;
  introEn: string | null;
  founderOneName: string;
  founderOneNameEn: string | null;
  founderOneRole: string;
  founderOneRoleEn: string | null;
  founderOneDescription: string;
  founderOneDescriptionEn: string | null;
  founderOneImageUrl: string;
  founderOneImageAssetId: string | null;
  founderOneImageAlt: string | null;
  founderOneImageAltEn: string | null;
  founderTwoName: string;
  founderTwoNameEn: string | null;
  founderTwoRole: string;
  founderTwoRoleEn: string | null;
  founderTwoDescription: string;
  founderTwoDescriptionEn: string | null;
  founderTwoImageUrl: string;
  founderTwoImageAssetId: string | null;
  founderTwoImageAlt: string | null;
  founderTwoImageAltEn: string | null;
  historyTitle: string;
  historyTitleEn: string | null;
  historyContentHtml: string;
  historyContentHtmlEn: string | null;
  translations: {
    locale: string;
    eyebrow: string | null;
    title: string | null;
    intro: string | null;
    founderOneName: string | null;
    founderOneRole: string | null;
    founderOneDescription: string | null;
    founderOneImageAlt: string | null;
    founderTwoName: string | null;
    founderTwoRole: string | null;
    founderTwoDescription: string | null;
    founderTwoImageAlt: string | null;
    historyTitle: string | null;
    historyContentHtml: string | null;
  }[];
};
